version: "3"

services:
  spring-app:
    image: postgres-app:latest
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    ports:
      - "5430:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: leiberbertel
      POSTGRES_DB: leiber-market

  pgAdmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin-data:
